cse110-fa21-group22/cse110-fa21-group22

components/ImageCard.js
components/RecipeCard.js

This removes the "Show All" button if this is something we'd like to do.

Removed the showall button

---

components/ImageCard.js
components/RecipeCard.js

Added functions for displaying recipe measurements without long repeating floats. 
Also added a capitalize method for displaying ingredients and equipment.

Formatting changes

---

components/RecipeCard.js
styles/recipeCard.css

Fixed some minor merge conflicts from adding the dropdown menu checkmark backend

Fixed some minor merge conflicts

---

components/RecipeCard.js
scripts/recipe.js
styles/recipe.css

make the pop-up work on recipe page

---

components/RecipeCard.js
components/UserList.js
components/UserLocalStorage.js

Red hearts

---

components/RecipeCard.js
components/UserList.js
components/UserLocalStorage.js
scripts/favorites.js
scripts/homepage.js

Favorite page select mode denis

---

components/RecipeCard.js
components/UserList.js
scripts/favorites.js
styles/favorite.css
webpages/favorite.html

Built on top of the move-favorite branch. This branch also adds functionality for removing favorites from edit mode on the favorites page.

Remove favorite

---

components/RecipeCard.js
components/UserList.js
scripts/favorites.js
styles/favorite.css
webpages/favorite.html

Implemented functionality for the move button on the favorites page.

Move favorites

---

components/RecipeCard.js

This change makes it so that when recipe cards have their recipe set, the recipe is checked against the master favorites list to determine if the heart should be filled red or not.

Fills favorite heart if recipe is in favorites

---

scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/searchpage.js
sw.js

Added a service worker cache so we use fewer api calls.

Implemented service worker to reduce api calls

---

components/RecipeCard.js
components/UserLocalStorage.js

Continued working off of Mitchell's branch. Finished populating dropdown with lists from user storage. Also fixed merge conflicts with the main branch.

Dropdown create new list fork

---

.eslintrc.json
admin/meetings/112221-meeting-TA.md
components/ImageCard.js
components/Navbar.js
components/RecipeCard.js
components/UserList.js
components/UserLocalStorage.js
scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
sw.js

Resolves #[add the issue number associated with your pull request here]

Fix files for linting

---

components/ImageCard.js
components/RecipeCard.js
components/UserList.js
components/UserLocalStorage.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
styles/UserList.css
styles/imagecard.css
styles/recipe.css
styles/recipeCard.css
sw.js
webpages/home.html

Resolves #[add the issue number associated with your pull request here]

refactor code

---

source/__tests__/favoriteRecipePage.test.js
source/__tests__/simpleFlow.test.js

Resolves #210 #209 #208 #207 
Added more E2E tests, specifically for the recipe page
Tests

Recipe Page Tests

---

components/RecipeCard.js
scripts/favorites.js
scripts/homepage.js
scripts/search.js

Resolves #216 
1) Update fetch URL
2) put calories number on the recipe card
Recipe card

Put calories on recipe card on all pages

---

styles/navbar.css

Resolves #229 
1) Modify navbar.css
Sidebar

Change the font color in sidebar to white

---

scripts/recipe.js
styles/recipe.css

Resolves #223 
1) Add a previous button
recipe.html

Add previous button

---

components/RecipeCard.js
components/UserLocalStorage.js
scripts/favorites.js
scripts/recipe.js

Resolves #241 
Modified the default list to be separate from the master-favorites list, hid the master-favorites list from the favorites page (added default list instead) to prevent edit list confusion 
Unhearting works still 
master-favorites is not displayed in dropdown or on the favorites page anymore

master-favorites hidden

---

scripts/favorites.js
scripts/homepage.js
scripts/search.js
webpages/home.html

Resolves #249 
Add a message to show no favorites
Message on home.html

Add a message saying no favorite added yet

---

.github/pull_request_template.md
admin/cipipeline/phase1.md
admin/meetings/110521-internal-meeting.md
admin/meetings/111921-internal-meeting.md
admin/meetings/112621-internal-meeting.md
admin/meetings/112621-retrospective2.md
admin/meetings/112621-sprint-2-review.md
admin/meetings/112921-meeting-with-TA.md
scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js
specs/adrs/102221-preloading-recipes.md
specs/adrs/110121-import-export.md
specs/adrs/112621-store-recipe-objects.md
styles/UserList.css
styles/favorite.css
styles/home.css
styles/imagecard.css
styles/navbar.css
styles/recipe.css
styles/recipeCard.css
styles/reset.css
styles/search.css
webpages/recipe.html

___
Ran prettier on all of the files
---
That the site still works

fix prettier

---

scripts/recipe.js
source/__tests__/end-to-end.test.js

___
Fix the bug with removing recipes from recipe page
---
When you unheart on recipe page, recipe is removed from all lists

fix bug with removing from master

---

components/RecipeCard.js
scripts/recipe.js
source/__tests__/end-to-end.test.js

---
Changed recipeCard.js and recipe.js to check if there is at least one list checked or the user has entered a new list to be added to
---
If you don't select a list to be added to, you get alert.
If you do put a list into the enter new list or pick at least one list, you don't.
I did this for recipeCards and on the recipe page.

ensure one box is checked

---

.github/pull_request_template.md
scripts/explore.js
scripts/index.js
scripts/spoonacular.js
source/__tests__/end-to-end.test.js
source/__tests__/unittest.test.js

---
Created a file for unit tests: unittest.test.js
Added refresh button test inside unittest.test.js --> Move refresh test to e2e 
Dummy test in unittest.test.js
Updated the PR instructions
---
Make sure that this test didn't affect other tests. 
One test exceed the test time limit.

Unit test refresh

---

styles/imagecard.css

Remove arrows on mobile

---

admin/meetings/120321-internal-meeting.md
components/Navbar.js
scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js

---
1) Delete the "search this" button
2) Delete "0-9999hr" filter
3) Make apply this and navbar both work for searching things
4) Make your searchTerm stay on the navbar
5) Hide the sidebar button on the home page, recipe page, and favorite page.
6) Make the previous and next works normal
---
1) Sidebar elements
2) Search functions whether work or not

Fix sidebar bugs

---

source/__tests__/end-to-end.test.js
styles/recipeCard.css

---
1) Change position:position to position:relative
---
Favorite page and home page recipe card dropdown menu

Fix dropdown place on home page

---

scripts/homepage.js
source/__tests__/end-to-end.test.js
webpages/home.html

---
1) Clean the homepage.js functions
---
homepage.js

Update homepage.js fetch function

---

README.md
admin/meetings/120321-internal-meeting.md
specs/adrs/110121-import-export.md

merge main

---

scripts/recipe.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js

---
fixed search.js
---
previously, when you search for a recipe that is more than one word, it combines it. For example, "ice cream" became "icecream"

Search name bug

---

scripts/homepage.js
scripts/recipe.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js
styles/recipe.css

---
1) Fix the previous button when only have two steps
2) Fix the previous button when only have one step
When only have one step, no button will show. And the step will be highlighted.
3) When no instruction, show "No Instruction"
---
Check recipeID = 421321, 321532 (Multiple steps)
recipeID =  783299 (two steps), 
recipeID = 631877 (one step)
recipeID = 715736 (no instruction)
Check every "previous", "next", and "restart" button
**Can be merged**

Fix previous button on recipe card

---

scripts/recipe.js
source/__tests__/end-to-end.test.js
styles/recipe.css
webpages/recipe.html

---
1) Change the css file
---
Any recipe page: email button

Change the email button position

---

components/RecipeCard.js
source/__tests__/end-to-end.test.js

---
delete code in recipecard.js which makes it dropdown if clicked
---
shouldn't show up when you click the heart and then cancel the confirmation of removing

hide dropdown if favorited

---

scripts/favorites.js
source/__tests__/end-to-end.test.js

---
1) If a favorites list is empty, display no favorites added instead of blank user list
---
Favorite page

Add a message saying "No Favorites Added Yet"

---

components/RecipeCard.js
components/UserLocalStorage.js
scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js

---
1) Change recipe-id to object which stored in localStorage
2) Modify corresponding functions
---
1) localStorage functions
2) Every line which uses localStorage function
3) The heart initialization on the every page
**Home Page:**
1) Add recipe from the home page to one list
2) Add recipe from the home page to multiple lists
3) Remove recipe from one list on the home page
4) Remove recipe from multiple lists on the home page
5) Jump from home page to recipe page by an unfavorite recipe
6) Jump from home page to recipe page by a favorite recipe
**Recipe Page:**
1) Add recipe from the home page to one list
2) Add recipe from the home page to multiple lists
3) Remove recipe from one list on the home page
4) Remove recipe from multiple …

Change local storage to store recipe objects

---

components/RecipeCard.js
components/UserLocalStorage.js
scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js

---
1) Fix the previous and next button when only have three steps
2) Change E2E-test line 347 to 10000ms
---
recipeID = 655620
**Merge #304 first**

Fix previous button

---

scripts/recipe.js
scripts/search.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js

---
1) Change the dropdown box position on recipe page on PC version
2) Fix the search term when searching things ("xxxx"" problem)
---
1) search term
2) dropdown box on recipe page

Fix dropdown position on recipe page

---

components/ImageCard.js
components/Navbar.js
components/RecipeCard.js
components/UserList.js
components/UserLocalStorage.js
scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js
styles/recipe.css

---
1) Initialize local storage on every page
2) Fix the restart button on the recipe page
---
1) recipeID = 715736, 655620, 321532, 631877
2) check favorite-master initialized when directly use each page url. (Not jump from home page)

Fix back button in mobile version

---

scripts/recipe.js
source/__tests__/end-to-end.test.js

---
recipe.js so that it wouldn't reload every time we fav or unfav a recipe
---
1. adding to a list would update storage and change to red heart, then unfavoring it would prompt user if they are sure and if cancel nothing happens, and if yes then remove from all lists that its in all with no reload
2. adding a custom list would appear on the dropdown (unfavor and then try favoring it again) and that it functions like above without reloading
3. make sure dropdown works properly only showing up when it isn't favorited and user clicks on heart

No reload recipe page

---

components/ImageCard.js
components/Navbar.js
components/RecipeCard.js
components/UserList.js
components/UserLocalStorage.js
scripts/favorites.js
scripts/homepage.js
scripts/recipe.js
scripts/search.js
scripts/searchpage.js
source/__tests__/end-to-end.test.js
webpages/home.html

---
1. Make the home page not refresh when the user favorite a recipe 
---
1. check when user create a list by favorite on one recipeCard, it should reflect on all other cards meaning that all other cards should have that list as option.

No refresh on home when addtofavorite

---

components/RecipeCard.js
source/__tests__/end-to-end.test.js

---
recipecard.js to not reload on search page
---
no reloading when you fav/unfav. lists are updated. storage is updated.
on my live server the dropdown pops up when i cancel the unfav and i cant check on the deploy preview (dont want to use any more points)

no reload on search page

---

assets/favorite-delete-list.svg
components/UserList.js
scripts/favorites.js
source/__tests__/end-to-end.test.js
styles/UserList.css

---
- Added a garbage can icon to favorites list in edit mode
- Restyled UserList title block for mobile and pc
- Added deleting an entire list in edit mode backend
- Deleting a list removes it from the page and localstorage
- Garbage can icon appears on all lists except 'My Favorites' in edit mode
- Styling looks appropriate on pc and mobile

Added deleting of user lists without having run ESLint or Prettier

---

src/components/RecipeCard.js
src/scripts/searchpage.js

---
pull this branch and run in liveserver since deployment API key is running out. 
homePage now do not refresh when a recipeCard is being favorited. 
searchPage do not refresh when a recipeCard is being favorited 
searchPage always showing side-bar-button(used to disappear for reason that I do not understand) 
1. homePage should not refresh 
2. searchPage should not refresh 
3. searchPage should have side-bar button both desktop and mobile

Home page searchpage no refresh working again

---

src/__tests__/end-to-end.test.js
src/webpages/recipe.html

---
Deleting recipe slang element.
---
Recipe slang removed from recipe pages.

small change

---

README.md
src/components/ImageCard.js
src/components/RecipeCard.js
src/components/UserList.js
src/components/UserLocalStorage.js
src/scripts/homepage.js
src/scripts/recipe.js
src/scripts/searchpage.js

---
added documentation for most files 
---
check DOC lnks

Update readme and doc

---

src/components/ImageCard.js

modified documentation
